services:
  - type: web
    name: erion-raven-api
    env: node
    plan: free
    buildCommand: pnpm install && pnpm turbo build --filter=@raven/api
    startCommand: pnpm --filter @raven/api start
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
    autoDeploy: false

