version: 0.1

build:
  commands:
    - cd ../.. && pnpm install
    - cd ../.. && pnpm --filter @raven/api build

start:
  command: cd ../.. && pnpm --filter @raven/api start

env:
  - key: NODE_ENV
    value: production

